// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoc038pECC2HXS8_uEJQNF4Ghb81A1yEE',
    appId: '1:929726493436:web:e542f9a44148b339addd79',
    messagingSenderId: '929726493436',
    projectId: 'todo-app-6cc2d',
    authDomain: 'todo-app-6cc2d.firebaseapp.com',
    storageBucket: 'todo-app-6cc2d.appspot.com',
    measurementId: 'G-HXRGHXCXK2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5EDB8Dlys6GCzOHod2kVgGri6s1S5iz0',
    appId: '1:929726493436:android:519e2be1f5a2947aaddd79',
    messagingSenderId: '929726493436',
    projectId: 'todo-app-6cc2d',
    storageBucket: 'todo-app-6cc2d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGs-QrfOoxFp9bamCXgwUPIXP7LZds6M4',
    appId: '1:929726493436:ios:dbcedc54e3051b44addd79',
    messagingSenderId: '929726493436',
    projectId: 'todo-app-6cc2d',
    storageBucket: 'todo-app-6cc2d.appspot.com',
    iosClientId: '929726493436-fvbotssoc1j1h5kmc10llrivs3pvqdsa.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGs-QrfOoxFp9bamCXgwUPIXP7LZds6M4',
    appId: '1:929726493436:ios:dbcedc54e3051b44addd79',
    messagingSenderId: '929726493436',
    projectId: 'todo-app-6cc2d',
    storageBucket: 'todo-app-6cc2d.appspot.com',
    iosClientId: '929726493436-fvbotssoc1j1h5kmc10llrivs3pvqdsa.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );
}
